version: '3.8'

services:
  mysql-dlk:
    image: mysql:latest
    container_name: mysql-dlk
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: datalakes_staging
      MYSQL_USER: datalakes_user
      MYSQL_PASSWORD: securepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dlk-network

  mongodb-dlk:
    image: mongo:latest
    container_name: mongodb-dlk
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dlk-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-dlk
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-dlk
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - dlk-network

volumes:
  mysql_data:
  mongodb_data:

networks:
  dlk-network:
    driver: bridge
